- name: expanding extended partition
  command: growpart /dev/sda 2
  ignore_errors: true
  tags:
    - drives

- name: expanding root partition
  command: growpart /dev/sda 5
  ignore_errors: true
  tags:
    - drives

- name: expanding root filesystem
  command: resize2fs /dev/sda5
  ignore_errors: true
  tags:
    - drives
